apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gestaopedidos-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - host: gestaopedidos.internal.mycompany.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gestaopedidos-service
                port:
                  number: 80
