name: CI/CD Pipeline

on:
  push:
    branches:
      - '**' # Roda o CI em qualquer branch
  pull_request:
    branches:
      - main # Roda o CD apenas na branch main

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: your-cluster-name
  IMAGE_REPOSITORY: your-docker-repo-name

jobs:
  # Job de Build e Testes (CI)
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build and Test
      - name: Build and Test with Maven
        run: mvn clean verify